### ISSUE TITLE
The JADE package is not automatically installed

### ISSUE THREAD

**Issue by wldevries** [dngoins/Kinectv2HeartRate#1]
I had to install it manually in the R console using the command `install.packages("JADE")`

**Comment by dngoins** [comment]
In the InitializeR() function in the WPF application, JADE is installed when the .Net R engine proxy is initialized. It assumes you have connectivity to the network. However you can move the install.packages("JADE") command to the script, I just found that sometimes that takes longer to execute and process so I move it outside of the script and into the startup process.

After you manually install it you must load it up in your session with the R command: library(JADE)

HTH

**Comment by cefoot** [comment]
I had to change the Line:

```
engine.Evaluate("install.packages('JADE', repos='http://cran.rstudio.com/bin/windows/contrib/3.2/JADE_1.9-92.zip'")
```

to this line:

```
engine.Evaluate("install.packages('JADE', repos='http://cran.rstudio.com/')")
```

than it worked for me ;)

**Comment by dngoins** [comment]
Oh yes the repository url. I was using the Azure ML R repository URL, because I wanted to see how well the results tested in Azure ML. The one above from cefoot is the standard one for R-Studio.

Thank you cefoot.

**Comment by cefoot** [comment]
you're welcome! And thank you for the great example! ;D
