### ISSUE TITLE
After the 30 second countdown an RDotNet.EvaluationException is thrown

### ISSUE THREAD

**Issue by wldevries** [dngoins/Kinectv2HeartRate#2]
Exception thrown: 'RDotNet.EvaluationException' in RDotNet.dll

```
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  more columns than column names
```

I have no experience at all with R, but can look up more details if needed.

**Comment by dngoins** [comment]
The error comes from: R's read.csv function. 

This means that when running the WPF app, the csv file that was created for some reason didn't properly encode the '/r/n' data with the correct information. R expects the csv files to start (first row) with the column header information. I create a first row of header values, then the actual values follow separated by carriage return line feed and obviously each column by comma. Try running the sample with R x86 32 bit, and compiling the project in 32bit. I'm pretty sure this is an encoding issue somewhere.

**Comment by cefoot** [comment]
For me this was an problem with the culture ;)

changed line:

```
string data = string.Format("{0},{1},{2},{3},{4},{5}\n", m_secondsElapsed.ElapsedMilliseconds, norm_alpha, norm_red, norm_green, norm_blue, norm_ir);
```

to

```
string data = string.Format(new System.Globalization.CultureInfo("en-GB"), "{0},{1},{2},{3},{4},{5}\n", m_secondsElapsed.ElapsedMilliseconds, norm_alpha, norm_red, norm_green, norm_blue, norm_ir);
```

in MainWindow.xaml.cs .. private void RecordData(RectI faceRegion, FaceFrame faceFrame)

see:
https://github.com/cefoot/Kinectv2HeartRate/commit/fa038570a39cfecbb58a173ce6993b6f47d7f626
