### ISSUE TITLE
System.FormatException in mscorlib.dll

### ISSUE THREAD

**Issue by GemmaMaria** [dngoins/Kinectv2HeartRate#8]
Hello! I'm trying to run the program but this message appears when the InitializeR() is invokated , do you know how to fix it?

thanks in advance!

**Comment by cefoot** [comment]
Have a look at my changes to MainWindow.xaml.cs I had to define globalization
https://github.com/cefoot/Kinectv2HeartRate/commit/fa038570a39cfecbb58a173ce6993b6f47d7f626

**Comment by GemmaMaria** [comment]
Thanks a lot for your coment but it still doesn't work. Although I updated both files, .csproj and MainWindow.xaml.cs,  the exception "System.Format.Extension" pops up in the same line,  engine = REngine.GetInstance();. I'm using R .NET and probably the error is related to the version. I'm a bit lost.

**Comment by GemmaMaria** [comment]
Now it works! thanks so much, It was my fault,  I didn't change the platform target.
